### ISSUE TITLE
Maybe a module is missing?

### ISSUE THREAD

**Issue by timscha** [svensp/hcloud_ocf#9]
Hello!
I tried your script, unfortunately I don't get it working:

pcs status

```
Full list of resources:

 Clone Set: mysql-service-clone [mysql-service] (promotable)
     Masters: [ fe00 ]
     Slaves: [ fe01 ]
 virtual_ip	(ocf::heartbeat:IPaddr2):	Started fe00
 floating_ip	(ocf::hetzner:floating_ip):	Stopped

Failed Resource Actions:
* floating_ip_start_0 on fe01 'unknown error' (1): call=51, status=complete, exitreason='',
    last-rc-change='Sat Feb  6 18:08:45 2021', queued=0ms, exec=581ms
* floating_ip_start_0 on fe00 'unknown error' (1): call=57, status=complete, exitreason='',
    last-rc-change='Sat Feb  6 18:08:45 2021', queued=0ms, exec=533ms
```

The pacemaker.log shows errors like this:

```
Feb 06 18:11:43 MyHostName pacemaker-schedulerd[745] (unpack_rsc_op_failure) 	warning: Processing failed start of floating_ip on fe01: unknown error | rc=1
Feb 06 18:11:43 MyHostName pacemaker-schedulerd[745] (unpack_rsc_op_failure) 	warning: Processing failed start of floating_ip on fe00: unknown error | rc=1

```

```
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [ Traceback (most recent call last): ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [     "__main__", mod_spec) ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [     exec(code, run_globals) ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [   File "/usr/lib/ocf/resource.d/hetzner/floating_ip/__main__.py", line 26, in <module> ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [   File "/usr/lib/ocf/resource.d/hetzner/floating_ip/ocf.py", line 121, in run ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [   File "/usr/lib/ocf/resource.d/hetzner/floating_ip/floating_ip.py", line 190, in monitor ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [   File "/usr/lib/ocf/resource.d/hetzner/floating_ip/floating_ip.py", line 114, in findServer ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [   File "/usr/lib/ocf/resource.d/hetzner/floating_ip/shared.py", line 94, in find ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [   File "/usr/local/lib/python3.7/dist-packages/hetznercloud/servers.py", line 70, in get_all ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [     yield HetznerCloudServer._load_from_json(self._config, result) ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [   File "/usr/local/lib/python3.7/dist-packages/hetznercloud/servers.py", line 317, in _load_from_json ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [     cloud_server.outgoing_traffic = int(json["outgoing_traffic"]) ]
Feb 06 18:08:44 MyHostName pacemaker-execd     [743] (operation_finished) 	notice: floating_ip_monitor_0:10963:stderr [ TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' ]
Feb 06 18:08:44 MyHostName pacemaker-controld  [746] (process_lrm_event) 	notice: Result of probe operation for floating_ip on fe00: 1 (unknown error) | call=55 key=floating_ip_monitor_0 confirmed=true cib-update=463
Feb 06 18:08:44 MyHostName pacemaker-controld  [746] (process_lrm_event) 	notice: fe00-floating_ip_monitor_0:55 [ Traceback (most recent call last):\n  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/usr/lib/ocf/resource.d/hetzner/floating_ip/__main__.py", line 26, in <module>\n  File "/usr/lib/ocf/resource.d/hetzner/floating_ip/ocf.py", line 121, in
Feb 06 18:08:44 MyHostName pacemaker-based     [740] (cib_perform_op) 	info: +  /cib/status/node_state[@id='1']/lrm[@id='1']/lrm_resources/lrm_resource[@id='floating_ip']/lrm_rsc_op[@id='floating_ip_last_0']:  @transition-magic=0:1;5:325:7:56d79776-3d6a-44c3-8ce0-17dc809031a8, @call-id=55, @rc-code=1, @op-status=0, @exec-time=833
Feb 06 18:08:44 MyHostName pacemaker-based     [740] (cib_perform_op) 	info: ++ /cib/status/node_state[@id='1']/lrm[@id='1']/lrm_resources/lrm_resource[@id='floating_ip']:  <lrm_rsc_op id="floating_ip_last_failure_0" operation_key="floating_ip_monitor_0" operation="monitor" crm-debug-origin="do_update_resource" crm_feature_set="3.1.0" transition-key="5:325:7:56d79776-3d6a-44c3-8ce0-17dc809031a8" transition-magic="0:1;5:325:7:56d79776-3d6a-44c3-8ce0-17dc809031a8" exit-reason="" on_node="fe00" cal
Feb 06 18:08:44 MyHostName pacemaker-controld  [746] (status_from_rc) 	warning: Action 5 (floating_ip_monitor_0) on fe00 failed (target: 7 vs. rc: 1): Error
Feb 06 18:08:44 MyHostName pacemaker-controld  [746] (abort_transition_graph) 	info: Transition 325 aborted by operation floating_ip_monitor_0 'modify' on fe00: Event failed | magic=0:1;5:325:7:56d79776-3d6a-44c3-8ce0-17dc809031a8 cib=0.36.4 source=match_graph_event:297 complete=false
```

For me it's looks like a module is missing or something similar?
I am grateful for any help.

**Comment by svensp** [comment]
Hi,

it is not quite a missing module but code inside the `hetznercloud` module is erroring out because it cannot parse the field "outgoing_traffic". It expects the field to be a number (may or may not be in string format) but receives 'None' instead.

This is strange because according to the documentation the field is supposed to exist and have a number in it.

If you only use the hetznercloud python module for the agent(which you should, it is deprecated) you could try adding a print statement to see what the actual result looks like

In `/usr/local/lib/python3.7/dist-packages/hetznercloud/servers.py` line 317 change:
```python
cloud_server.outgoing_traffic = int(json["outgoing_traffic"]) ]
```

to

```python
print(json)
cloud_server.outgoing_traffic = int(json["outgoing_traffic"]) ]
```

you will still receive the error message but it should also  print the api response it is working with. We'll probably find the problem there.

**Comment by timscha** [comment]
Thank you @svensp! I recreated the API key and created a new floating ip, after this it was working. So I guessing their was a copy misstake or something similar.

Regarding the depcreated module, Is there any chance that you will do a rewrite or what be a future proof solution?
